name: Deploy "little project"
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
        working-directory: ./little-project
      - name: Test code
        run: npm run test
        working-directory: ./little-project
      - name: Build code
        run: npm run build
        working-directory: ./little-project

